version: '3.8'

services:
  sql-server:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlServer
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  catalog-api:
    image: ${DOCKER_REGISTRY-}jcpcatalogapi
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - PORT=80
      - PATH_BASE=/catalog-api
      - SQL_HOSTNAME=sql-server
      - SQL_PORT=1433
    ports:
      - "5020:80"
      - "2021:443"
    build:
      context: .
      dockerfile: Services/Catalog/Presentation/JCP.Catalog.API/Dockerfile
    restart: on-failure
    depends_on:
      - sql-server
      - rabbitmq

  ordering-api:
    image: ${DOCKER_REGISTRY-}jcporderingapi
    container_name: ordering-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - PORT=80
      - PATH_BASE=/ordering-api
      - SQL_HOSTNAME=sql-server
      - SQL_PORT=1433
    ports:
      - "5010:80"
      - "5011:443"
    build:
      context: .
      dockerfile: Services/Ordering/Presentation/JCP.Ordering.API/Dockerfile
    restart: on-failure
    depends_on:
      - sql-server
      - rabbitmq

  jcp-ordering-bff:
    image: ${DOCKER_REGISTRY-}jcporderingbff
    container_name: jcp-ordering-bff
    build:
        context: .
        dockerfile: ApiGateways/JCP.Ordering.BFF/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__grpcCatalog=http://catalog-api:80
    depends_on:
      - sql-server
      - ordering-api
      - catalog-api
    ports:
      - "5030:80"

volumes:
  mssql-server-linux-data: