version: '3.4'

services:
  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=80
      - PATH_BASE=/catalog-api
    ports:
      - "5101:80"
      - "5111:443"
  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/ordering-api
      - PORT=80
    ports:
      - "5102:80"
      - "5112:443"
