version: '3.4'

services:
  catalog-api:
    image: ${DOCKER_REGISTRY-}jcpcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/JCP.Catalog.API/Dockerfile

  ordering-api:
    image: ${DOCKER_REGISTRY-}jcporderingapi
    build:
      context: .
      dockerfile: Services/Ordering/JCP.Ordering.API/Dockerfile

  identityserver-api:
    image: ${DOCKER_REGISTRY-}jcpidentityserver
    build:
      context: .
      dockerfile: Services/Identity/JCP.IdentityServer.API/Dockerfile