name: jcp-shop .NET 5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Back/Services/Ordering/JCP.Ordering.API
    - name: Build
      run: dotnet build ./Back/Services/Ordering/JCP.Ordering.API --no-restore
    - name: Test
      run: dotnet test ./Back/Services/Ordering/JCP.Ordering.API --no-build --verbosity normal
